// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9iDoQLUrcZTWB3hGMWaYDTmY3qkhy-44',
    appId: '1:460632623868:web:99e690b32825ec64a6e579',
    messagingSenderId: '460632623868',
    projectId: 'scansol-platform-2026',
    authDomain: 'scansol-platform-2026.firebaseapp.com',
    storageBucket: 'scansol-platform-2026.firebasestorage.app',
    measurementId: 'G-4GSVTQE8HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdupJt3-nspyZD9F9IgIIDRLqwR7zc-O8',
    appId: '1:460632623868:android:4aef907f993bd040a6e579',
    messagingSenderId: '460632623868',
    projectId: 'scansol-platform-2026',
    storageBucket: 'scansol-platform-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1R9Owd0ESg0oR6Gfgla3Hwugq15krbAI',
    appId: '1:460632623868:ios:96d3cc41c78252f9a6e579',
    messagingSenderId: '460632623868',
    projectId: 'scansol-platform-2026',
    storageBucket: 'scansol-platform-2026.firebasestorage.app',
    iosBundleId: 'com.example.scansol2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1R9Owd0ESg0oR6Gfgla3Hwugq15krbAI',
    appId: '1:460632623868:ios:96d3cc41c78252f9a6e579',
    messagingSenderId: '460632623868',
    projectId: 'scansol-platform-2026',
    storageBucket: 'scansol-platform-2026.firebasestorage.app',
    iosBundleId: 'com.example.scansol2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9iDoQLUrcZTWB3hGMWaYDTmY3qkhy-44',
    appId: '1:460632623868:web:d893c4d993a1bceea6e579',
    messagingSenderId: '460632623868',
    projectId: 'scansol-platform-2026',
    authDomain: 'scansol-platform-2026.firebaseapp.com',
    storageBucket: 'scansol-platform-2026.firebasestorage.app',
    measurementId: 'G-6S2Q4J94XG',
  );

}